### ISSUE TITLE
What may have caused the extra noise added to a face during inference after adapting the current code framework in liveTalking from ernerf to Synctalk?

### ISSUE THREAD

**Issue by EYcab** [ZiqiaoPeng/SyncTalk#238]
![0](https://github.com/user-attachments/assets/25edf20c-74b5-4496-a6b5-d37c1fd59aa1)
The inference of my model based on SyncTalk work perfectly fine, but after adapting this model to liveTalking codes based on the ERNERF approach, there was noise added to her face.

Please give me some hints on handling this issue. Thank you in advance.

This is also posted on https://github.com/lipku/LiveTalking/issues/302

**Comment by nguyenchiminhhieu** [comment]
Hello,
I'm really excited to see this issue of yours! I'm also exploring the possibility of using the SyncTalk model instead of ER-NeRF as currently implemented in the repo. Could you guide me on how to make this transition?

I'm new to this, so detailed instructions would be incredibly helpful. Thank you so much for your kindness!

Best regards,
